server:
  port: 6060


spring:
  profiles:
    active:
  activiti:
    history-level: full
    db-history-used: true
    database-schema-update: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti5?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123456